language: node_js
node_js:
  - "12"

addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi

install:
  - npm install

after_success:
  - cat coverage/lcov.info | coveralls

cache:
  directories:
    - .vscode-test

notifications:
  email:
    on_success: never
    on_failure: always
